config/routes.rb
Rails.application.routes.draw do
  get 'shops/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'reservations#index'
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :shop

  def self.decrement(count_person)
    Shop.select(:capacity) - count_person
  end

  def remaining_seat(count_person)
    reservation.shop.capacity - count_person
  end

  # reservation.date.のday.のshop.capcty - count_person
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :reservations

  def remaining_seat(count_person)
    shop.capacity - count_person
  end

  def upper_limit
    capacity - reservation.count_person
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.create!(reservation_params)
    # フォームに入力した予約テーブルに紐づく、ショップテーブルのカラム：キャパシティの値を呼び出す - フォームに入力した予約の人数
    @shop = @reservation.shop.capacity - reservation_params[:count_person].to_i
    # キャパシティーが0以上ならtrue
    if @shop >= 0
      # 変更されたshopのcapacityの値を更新
      @reservation.shop.update(capacity: @shop)
      redirect_to shops_index_path
    else
      # キャパシティがマイナスになる場合はfalse
      redirect_to action: :index
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:shop_id, :count_person)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
    @seat = Shop.remaining_seat
  end

  private

  def shop_params
    params.require(:shop).permit(:capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReservationSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/_reservation.html.erb
<p>予約人数:<%= reservation.count_person%></p>

app/views/reservations/index.html.erb
<h2>予約</h2>
<%= link_to "新規予約", new_reservation_path%>
<%= link_to "予約可能人数", shops_index_path %>
<%= render @reservations %>

app/views/reservations/new.html.erb
<h2>新規予約</h2>
<%= form_with model: @reservation, local: true do |f| %>
  <%= f.text_field :shop_id, :value => 2 %>
  <p>来店人数：<%= f.text_field :count_person %></p>
  <%= f.submit "送信" %>
<% end %>

app/views/shops/_shop.html.erb
<p>予約可能日と結びつくID:<%= shop.id%></p>
<p>残りの予約可能人数:<%= shop.capacity%></p>

app/views/shops/index.html.erb
<h2>予約可能人数</h2>
<%= render @shops %>